paths:
  /api/todo/{userID}:
    get:
      tags:
        - Todo API
      summary: Returns all todo items for a user
      parameters:
        - in: path
          description: ID for the user. 
          name: userID
          type: integer
          produces:
            - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/item'

  /api/todo/{userID}/item/{itemID}:
    get:
      tags:
        - Todo API
      summary: Returns an item for a user.
      parameters:
        - in: path
          description: ID for the user. 
          name: userID
          type: integer
        - in: path
          description: Id for todo item. 
          name: itemID
          type: integer
          produces:
            - application/json
      responses:
        200:
          description: An array of todo items
          $ref: '#/definitions/item'

  /api/editItem/{userID}/item/{itemID}/status/{statusID}/itemName/{itemName}:
    put:
      tags:
        - Todo API
      summary: Edit a todo item
      parameters:
        - in: path
          description: ID for the user. 
          name: userID
          type: integer
        - in: path
          description: Id for todo item. 
          name: itemID
          type: integer
        - in: path
          description: New status for the item. 
          name: statusID
          type: integer  
        - in: path
          description: Item Description.
          name: itemName
          type: string
          produces:
            - application/json
      responses:
        200:
          description: OK if item was updated.
          $ref: '#/definitions/item'

  /api/addItem/{userID}/itemName/{itemName}:
    post:
      tags:
        - Todo API
      summary: Create a todo item.
      parameters:
        - in: path
          description: ID for the user. 
          name: userID
          type: integer
        - in: path
          description: Item Description.
          name: itemName
          type: string
          produces:
            - application/json
      responses:
        200:
          description: OK if new todo item is created.
          $ref: '#/definitions/item'